apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appConfig.secretName | default (printf "%s-secret" (include "metrics-app.fullname" .)) }}
  labels:
    {{- include "metrics-app.labels" . | nindent 4 }}
type: Opaque
data:
  # The value for the secretKey (e.g., PASSWORD) is taken from values.yaml and base64 encoded.
  # Example: .Values.appConfig.passwordValue "MYPASSWORD" becomes "TVlQQVNTV09SRA==" when encoded.
  {{ .Values.appConfig.secretKey }}: {{ .Values.appConfig.passwordValue | b64enc | quote }}