{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "metrics-app.serviceAccountName" . }}
  labels:
    {{- include "metrics-app.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.serviceAccount.automount }}
# automountServiceAccountToken defaults to true in Kubernetes for a ServiceAccount if not specified.
# However, explicitly setting it based on values.yaml provides clarity.
# If you truly want to rely on the default K8s behavior for automounting, you can omit this block.
# But if .Values.serviceAccount.automount is set to false, you MUST set this to false.
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- else }}
# If .Values.serviceAccount.automount is explicitly false
automountServiceAccountToken: false
{{- end }}
{{- end -}}